# Streamlit settings
PAGE_TITLE: "House Price Prediction"
PAGE_ICON: "static/img/home.png"
LAYOUT: "wide"

PAGE_TITLE_PROFILE: "Profile"
PAGE_ICON_PROFILE: "static/img/profile.png"
LAYOUT_PROFILE: "wide"

PAGE_TITLE_ANALYTICS: "Analytics"
PAGE_ICON_ANALYTICS: "static/img/analysis.png"
LAYOUT_ANALYTICS: "wide"

# Data Configuration
train_data_path: "artifacts/train.csv"
test_data_path: "artifacts/test.csv"
preprocessing_path: "models/preprocessing"
METRICS_PATH: "artifacts/metrics.json"
FEATURE_IMPORTANCE_PATH: "artifacts/feature_importance.json"

# MLflow Configuration
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "house_price_prediction"
  artifact_path: "model"

model_params:
  random_forest_regressor:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    random_state: 42

  gradient_boosting_regressor:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42

columns_to_drop:
  - "Id"
  - "PoolQC"
  - "MiscFeature"
  - "Alley"
  - "Fence"
  - "FireplaceQu"

FEATURE_COLUMNS:
  - "OverallQual"
  - "YearBuilt"
  - "YearRemodAdd"
  - "TotalBsmtSF"
  - "1stFlrSF"
  - "GrLivArea"
  - "FullBath"
  - "TotRmsAbvGrd"
  - "GarageCars"
  - "GarageArea"
  - "MSZoning"
  - "Utilities"
  - "BldgType"
  - "Heating"
  - "KitchenQual"
  - "SaleCondition"
  - "LandSlope"

NUMERICAL_FEATURE_COLUMNS:
  - "OverallQual"
  - "YearBuilt"
  - "YearRemodAdd"
  - "TotalBsmtSF"
  - "1stFlrSF"
  - "GrLivArea"
  - "FullBath"
  - "TotRmsAbvGrd"
  - "GarageCars"
  - "GarageArea"

TARGET_COLUMN:
  - "SalePrice"